[package]
name = "test-macros"
version = "0.1.0"
authors = ["Andre Richter <andre.o.richter@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.17"
quote = "1.0.6"
syn = { version = "1.0.29", features = ["full"] }
test-types = { path = "../test-types" }
